# 15. Python - Algorithmie 

## 1. Bases

#### 1. Simple échange

Ecrire un algorithme permettant d'échanger les valeurs de deux variables a et b.

In [3]:
a = 40
b = 50

print(a,b)

a,b = b,a

print(a,b)


40 50
50 40


#### 2. Le carré

Ecrire une fonction qui demande un nombre à l’utilisateur, puis qui calcule et affiche le carré de ce nombre.

In [7]:

def square () :
    x = float(input(" entrer un nombre "))
    return x**2


In [8]:
square()

 entrer un nombre 8.8


77.44000000000001

#### 3. Condition

Ecrire une fonction qui demande un nombre à l’utilisateur, et l’informe ensuite si ce nombre est positif ou négatif.

In [14]:
def nombre():
    n = float(input(" entrer un nombre "))

    if n > 0:
        print("le nombre",n,"est positif")
    elif n < 0 :
        print("le nombre",n,"est négatif")
    else:
        print("le nombre",n,"est nul")
nombre()


 entrer un nombre 0
le nombre 0.0 est nul


#### 4. Produit

Ecrire un algorithme qui prend entrée deux nombres qui vérifie si leur produit est négatif ou positif. Attention toute fois : on ne doit pas calculer le produit des deux nombres.

In [24]:
x = int( input("Veuillez entrer votre premier nombre: ") )
y = int( input("Veuillez entrer votre second nombre: ") )
   
if ( x * y > 0 ) :
    print('leur produit est positif')
elif x * y == 0:
    print('leur produit est nul')
else:
    print('leur produit est négatif')

Veuillez entrer votre premier nombre:1
Veuillez entrer votre second nombre:5
leur produit est positif


#### 5. Calcul

Ecrire une fonction qui demande un nombre de départ, et qui ensuite affiche les dix nombres suivants. Par exemple, si l’utilisateur entre le nombre 17, le programme affichera les nombres de 18 à 27.

In [25]:
def suite():

    x = int(input('entrez un nombre:'))
    #res = 
    return('les 10 nombres suivants sont:',list(range(x+1, x+11)))

suite()

entrez un nombre:5


('les 10 nombres suivants sont:', [6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

In [26]:
def les_suiv():
    
    nb = int(input("entrer un nombre: "))
    nlst = []
    
    cpt = 0
    
    while cpt < 10:
        
        cpt = cpt + 1
        nlst.append(nb + cpt)
        
    return nlst

les_suiv()

entrer un nombre: 5


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

#### 6. Additivité

Ecrire une fonction qui demande un nombre de départ, et qui calcule la somme des entiers jusqu’à ce nombre. Par exemple, si l’on entre 5, le programme doit calculer: 1+2+3+4+5=15.


In [42]:
def f():
    
    n = int(input("Entrer un nombre:"))
    cpt=0
    for i in range(0,n+1):
        cpt = cpt + i
        
    return("La somme des valeurs 1+2+...+n est",cpt)



In [43]:
f()

Entrer un nombre:5


('La somme des valeurs 1+2+...+n est', 15)

## 2. Tableau

#### 1. Somme

Ecrire un algorithme calculant la somme des valeurs d’un tableau (on suppose bien sur que le tableau a été préalablement saisi). **(NE PAS UTILISER LA FONCTION SUM)**

In [44]:
tab = np.array([1,2,3,4])
i= 0;tot = 0

while i < len(tab):
    tot = tot + tab[i]
    i = i + 1
print(tot)

10


#### 2. Double somme


Ecrire un algorithme constituant un tableau, à partir de deux tableaux de même longueur préalablement saisis. Le nouveau tableau sera la somme des éléments des deux tableaux de départ.

In [45]:
tab2 = np.array([1,2,3,4,5])
tab1 = tab2.copy()

print(tab1)
print(tab2)

t3 = np.array([])

[1 2 3 4 5]
[1 2 3 4 5]


In [46]:
if len(tab1)==len(tab2):
    
    for x in range(0,len(tab1)):
        
        t3 = np.append( t3,tab1[x]+tab2[x] )
else:
    print('erreur')

print(t3)

[ 2.  4.  6.  8. 10.]


In [51]:
tab1 = np.array([1,2,3,4])
tab2 = np.array([5,6,7,8])

tab3 = []

i= 0
while i < len(tab1):
    
    tab3.append(tab1[i] + tab2[i])
    i = i + 1
tab3 = np.array(tab3)
print(tab3)

[ 6  8 10 12]


#### 3. Fac Product

Toujours à partir de deux tableaux précédemment saisis, écrire un algorithme qui calcule le ’FacProduct’ des deux tableaux. Pour calculer le ’FacProduct’, il faut multiplier chaque élément du tableau1 par chaque élément du tableau2, et additionner le tout.

In [54]:
A=np.arange(10,20)
B=np.arange(20,30)

F=np.array([i*j for i in A for j in B])
print(F)


[200 210 220 230 240 250 260 270 280 290 220 231 242 253 264 275 286 297
 308 319 240 252 264 276 288 300 312 324 336 348 260 273 286 299 312 325
 338 351 364 377 280 294 308 322 336 350 364 378 392 406 300 315 330 345
 360 375 390 405 420 435 320 336 352 368 384 400 416 432 448 464 340 357
 374 391 408 425 442 459 476 493 360 378 396 414 432 450 468 486 504 522
 380 399 418 437 456 475 494 513 532 551]


#### 4. Le plus grand

Ecrire un algorithme permettant à l’utilisateur de renvoyer la plus grande valeur du tableau passer en entrée en précisant quelle position elle occupe dans le tableau. **(NE PAS UTILISER LA FONCTION MAX)**

In [55]:
def val_max(lst):
    
    maxlst = lst[-1] # stocker le max on le choisit aléatoirement 
    
    for i in lst:
        #print(lst[i])
        if i > maxlst:
        #print(maxlst)
            maxlst = i
            a1 = maxlst
            a2 = lst.index(maxlst)
            
    return("valeur max: ", a1,"position dans la liste donnée: ", a2)
        
lst1 = [1, -5, 4, 5, 8, 23, 30, 15, 5, 2]
val_max(lst1)

('valeur max: ', 30, 'position dans la liste donnée: ', 6)

#### 5. Plus grand que la moyenne

Ecrire un algorithme permettant à l’utilisateur de renvoyer le nombre de valeurs supérieures à la moyenne d’un tableau passé en input.

In [57]:
liste2 = [13,15,22,25,26]
s=0

for i in range(0,len(liste2)):
    s = s + liste2[i]
        
moyenne = s / len(liste2)
print(moyenne)

## 

cp = 0
for i in liste2:
    if i > moyenne:
        cp+=1
print(cp)

20.2


#### 6. Les vecteurs

Ecrire un algorithme permettant d’effectuer la multiplication de deux vecteurs de taille N connue à l’avance et d’afficher le résultat. **(NE PAS UTILISER LES FONCTIONS PYTHON : TOUT EST A CODER)**

In [ ]:
v = np.array([1,2,3])
v1 = np.array([4,5,6])

print(v,v1,np.multiply(v,v1))

N = len(v)
v2 = [None] * N

for i in range(N):
    v2[i] = v[i]*v1[i]
print(v2)

#### 7. Tri

Ecrire un algorithme triant un tableau. On va commencer à chercher l’élément de plus petite valeur dans le tableau, on le place en tête du tableau et on recommence avec le tableau moins la première case. **(NE PAS UTILISER LES FONCTIONS PYTHON : TOUT EST A CODER)**

In [ ]:
def selection_sort(arr):
    for i in range(len(arr)):
        minimum = i
       
        for j in range(i, len(arr)):
            # Sélection la plus petite valeur
            if arr[j] < arr[minimum] :
                minimum = j
       
        arr[minimum], arr[i] = arr[i], arr[minimum]
           
    return arr
arr = np.array([5, 2, 4, 3])
resultat = selection_sort(arr)
print(resultat)