# 19. Python - Révisions

**1. Créer une liste L1 contenant tous les entiers entre 1 et 100.**

In [1]:
L1 = list(range(1,101))
print(L1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


**2. Créer une fonction appelée ispair qui prend en argument un nombre et retour True si le nombre est pair et False sinon.**

In [2]:
def ispair(n):
    if n%2==0:
        return True
    else :
        return False
ispair(2)

True

**3. Compléter le script de la fonction list_ispair qui prend en argument une liste et qui retourne une liste contenant les nombres pairs contenus dans la liste de départ en remplaçant les XXX par le code adéquat.**

In [ ]:
def list_ispair(liste):
    listpair = XXX
    for XXX in XXX:
        if XXX:
            XXX
    return listpair
    

In [3]:
def list_ispair(liste):
    
    listpair = []
    
    for i in liste:
        if i%2==0:
            listpair.append(i)
            
    # deuxième possibilité Compréhension
    
    #for i in range(len(liste)):
        #if liste[i] % 2 == 0:
         #   listpair.append(liste[i])
            
    return listpair


list_ispair([2,3,9,10,11,13,14])

[2, 10, 14]

**4. Appliquer la fonction précédente à la liste `L_test` et stocker le résultat dans une variable appelée `pair`.**

In [5]:
L_test = [4,5,6,7,8,11,12,44,55,66]

In [6]:
pair = list_ispair(L_test)
print(pair)
print(type(pair))

[4, 6, 8, 12, 44, 66]
<class 'list'>


**5. Afficher l'index du nombre 55 de la liste `L_test`.**

In [7]:
print(L_test)

L_test.index(55)

[4, 5, 6, 7, 8, 11, 12, 44, 55, 66]


8

**6. Supprimer la valeur 55 de la liste.**

In [8]:
print(L_test)
del L_test[-2]
print(L_test)

[4, 5, 6, 7, 8, 11, 12, 44, 55, 66]
[4, 5, 6, 7, 8, 11, 12, 44, 66]


In [9]:
L_test = [4,5,6,7,8,11,12,44,55,66]
L_test.remove(55)
print(L_test)

[4, 5, 6, 7, 8, 11, 12, 44, 66]


**7. En utilisant une boucle, affichez tous les caractères (espaces compris), un à un, de la chaîne de caractères ci-bas.**

In [13]:
chaine = "Le confinement c'est cool !"
print(chaine)

Le confinement c'est cool !


In [12]:
for i in chaine:
    print(i)

L
e
 
c
o
n
f
i
n
e
m
e
n
t
 
c
'
e
s
t
 
c
o
o
l
 
!


**8. En utilisant la librairie adéquate, créer un vecteur V1 contenant les valeurs 1, 2, 3 et un vecteur V2 contenant les valeurs 4, 5, 6.**

In [14]:
import numpy as np

V1 = np.array([1,2,3])
V2 = np.array([4,5,6])

print(V1)
print(V2)

[1 2 3]
[4 5 6]


**9. Calculer la norme L2 du vecteur V3 ci-dessous.**

In [16]:
V3 = np.array([2,2,2])

In [19]:
L2 = np.linalg.norm(V3,2) # norme 2 par défaut 
print (L2)
import math
print (math.sqrt(12))

3.4641016151377544
3.4641016151377544


**10. Créer la matrice `A` suivante.**

$$A = \begin{bmatrix} 1 & -11 & 5 \\ 2 & -15 & 8 \\ 12 & 7 & 6 \end{bmatrix}$$


In [20]:
A = np.array([[1,-11,5],[2,-15,8],[12,7,6]])
print(A)

[[  1 -11   5]
 [  2 -15   8]
 [ 12   7   6]]


**11. Calculer le déterminant de A.**

In [21]:
np.linalg.det(A)

-100.00000000000004

**12. Calculer l'inverse de A que vous noterez A_inv.**

In [22]:
A_inv = np.linalg.inv(A)

print(A_inv)

[[ 1.46 -1.01  0.13]
 [-0.84  0.54 -0.02]
 [-1.94  1.39 -0.07]]


**13. Créer la matrice identité de taille 10 que vous noterez Id_10.**

In [24]:
import numpy as np
Id_10 = np.eye(10) # 
print(Id_10)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [25]:
Id_10 = np.identity(10) #identity 
print(Id_10)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


**14. Créer une fonction `f` qui calcule l'image de la fonction f(x) suivante pour un x donné f(x) = 3x + 6 puis calculer f(2) pour vérification.**

In [26]:
def f(x):
    return((3 * x) + 6)

f(2)

12

**15. En utilisant les fonctions lambda, créer une fonction `f1` qui calcule le carré d'un nombre. Tester la fonction avec le nombre 5.**

In [27]:
f1 = lambda x : x*x
f1(3)

9

**16. En utilisant les compréhensions de liste, recoder la fonction list_ispair de la question 3. Elle devra prendre en argument une liste de nombres et retourner une liste de nombres contenant les nombres entiers de la liste d'entrée. Vérifier son fonctionnement avec L_test.**

In [28]:
L_test = [4.0,5,6,7,8,11,12,44,55,66.7]

In [31]:
def list_ispair(liste):
    listentier = []
    [listentier.append(i) for i in liste if (i%2 == 0 or (i+1)%2 == 0)]
    
    return listentier

list_ispair(L_test)

[4, 5, 6, 7, 8, 11, 12, 44, 55]

In [32]:
def list_ispair(liste):
    
    listentier = [i for i in liste if (i%2 == 0 or (i+1)%2 == 0)]
    # Troncature : 15,67 => 15 # fonction trunc de numpy
    
    return listentier

list_ispair(L_test)

[4, 5, 6, 7, 8, 11, 12, 44, 55]

**17. Créer un set appelé `voy` qui contient les voyelles de l'alpjabet français.**

In [33]:
voy = set(['A','E','I','O','U','Y'])

print(voy)

{'O', ' A', 'I', 'Y', ' E', 'U'}


In [34]:
voy = set("aeiouy")
print (voy)

{'i', 'e', 'u', 'a', 'y', 'o'}


**18. Importer la librairie nécessaire aux calculs combinatoires et calculer toutes les permutations de `voy`. Combien de permutations existe-t-il?**

In [37]:
import itertools as it

all_perm = set(it.permutations(voy))
#print(all_perm)
len(all_perm) #(n!)

720

**19. On tire simultanément 2 boules parmi dans une urne contenant 6 boules rouges, 3 vertes et 2 boules noires indicernables au toucher.
Combien y-a-t-il de tirages possibles ? Vérifier votre réponse avec un script.**

In [38]:
import itertools

boules = {'r1','r2','r3','r4','r5','r6','v1','v2','v3','n1','n2'}
k = 2
T = set(itertools.combinations(boules,k))

print(T)
print(len(T)) # (k parmi n =  (n!)/k!(n-k)! )

{('v2', 'v1'), ('v3', 'r4'), ('v2', 'r2'), ('n1', 'r1'), ('r3', 'r6'), ('r2', 'r6'), ('v2', 'r5'), ('n1', 'r5'), ('r3', 'r2'), ('v2', 'r1'), ('v1', 'r3'), ('v3', 'r1'), ('n1', 'r2'), ('v3', 'n2'), ('v3', 'n1'), ('v3', 'r6'), ('v2', 'r4'), ('n1', 'n2'), ('n2', 'r3'), ('r4', 'r6'), ('n2', 'r2'), ('r3', 'r4'), ('r5', 'r6'), ('n2', 'r1'), ('r1', 'r4'), ('v1', 'r6'), ('v1', 'n1'), ('v1', 'n2'), ('v2', 'v3'), ('v1', 'r1'), ('v3', 'r3'), ('v2', 'r3'), ('r3', 'r5'), ('v2', 'r6'), ('n2', 'r4'), ('r5', 'r4'), ('n1', 'r6'), ('r3', 'r1'), ('r1', 'r2'), ('r1', 'r6'), ('n1', 'r3'), ('n1', 'r4'), ('v1', 'r4'), ('v1', 'r5'), ('v3', 'r2'), ('n2', 'r5'), ('r5', 'r1'), ('n2', 'r6'), ('r5', 'r2'), ('v2', 'n1'), ('r4', 'r2'), ('v1', 'v3'), ('v2', 'n2'), ('v1', 'r2'), ('v3', 'r5')}
55


In [40]:
T2 = set(itertools.permutations(boules,k))
print(T2)
print(len(T2))

{('r2', 'r1'), ('v2', 'r5'), ('r3', 'r2'), ('r4', 'v3'), ('r6', 'n1'), ('v1', 'r3'), ('n1', 'r2'), ('r3', 'r4'), ('r4', 'r5'), ('r2', 'v3'), ('v2', 'n2'), ('r2', 'r4'), ('v3', 'r3'), ('r4', 'n2'), ('r6', 'r4'), ('r5', 'n1'), ('n2', 'n1'), ('r1', 'r2'), ('n1', 'v3'), ('r4', 'v2'), ('r5', 'v1'), ('n2', 'r5'), ('r3', 'v2'), ('r2', 'n2'), ('r6', 'r3'), ('r5', 'r3'), ('v1', 'r2'), ('v2', 'v1'), ('v3', 'r4'), ('n2', 'v3'), ('n1', 'r1'), ('r3', 'r6'), ('r2', 'r6'), ('r1', 'r5'), ('v3', 'n1'), ('v3', 'r6'), ('n1', 'v2'), ('n2', 'r3'), ('r4', 'r6'), ('n2', 'r2'), ('r1', 'n1'), ('n2', 'r1'), ('r1', 'v3'), ('n2', 'r4'), ('r1', 'r6'), ('r5', 'v2'), ('n1', 'r3'), ('r1', 'r3'), ('r4', 'v1'), ('r5', 'r1'), ('r3', 'n2'), ('r6', 'r1'), ('v3', 'r5'), ('v2', 'r2'), ('r2', 'r5'), ('v3', 'r1'), ('r5', 'v3'), ('v3', 'n2'), ('n1', 'v1'), ('r6', 'v3'), ('r3', 'v3'), ('r3', 'v1'), ('r6', 'r5'), ('v3', 'v2'), ('v1', 'v2'), ('r5', 'r6'), ('r1', 'v1'), ('v1', 'n2'), ('v1', 'r1'), ('v2', 'r6'), ('r5', 'r4'), ('n1'

**20. Le type dictionnaire (ou tableau associatif ) permet de représenter des tableaux structurés. En effet, à chaque clé un dictionnaire associe une valeur, et cette valeur peut elle-même être une structure de donnée (liste, tuple ou un dictionnaire. . .).**

**Créer un dictionnaire vide appelé d. Ajouter y une clé `film` associée à une liste contenant 2 de vos films préférés.**

In [42]:
d = {}

print("le dictionnaire d créé", d, "est VIDE!" )



le dictionnaire d créé {} est VIDE!


In [43]:

d.update({"film": ["groundhog day", "time traveller's wife"]})
 

print("le dictionnaire d updaté: ", d)

le dictionnaire d updaté:  {'film': ['groundhog day', "time traveller's wife"]}


## 10)

### Écrire une fonction `moy` qui permet de calculer et d’afficher la moyenne de l’examen.

In [5]:
note = {'Florian':'abs',
        'Antoine':'12',
        'Clara':'15',
        'Robert':'0',
        'Agathe':'8',
        'Erwan':'7',
        'Zoé':'20',
        'Xavier':'11',
        'Didier':'20',
        'Alain':'0',
        'Hadi':'12'}
note

{'Florian': 'abs',
 'Antoine': '12',
 'Clara': '15',
 'Robert': '0',
 'Agathe': '8',
 'Erwan': '7',
 'Zoé': '20',
 'Xavier': '11',
 'Didier': '20',
 'Alain': '0',
 'Hadi': '12'}

In [8]:
 def moy(m):
    notes = [12, 15, 0, 8, 7, 20, 11, 20, 0, 12]
    Sn =  (12*2)+15+(0*2)+8+7+(20*2)+11
    m = Sn/len(notes)
    return('La moyenne de l examen est:',m)

In [7]:
moy(12)

('La moyenne de lexamen est:', 10.5)

In [14]:
import numpy as np
def moy ():
    l1 = []
    n1 = {key:val for key, val in note.items() if val != 'abs'}
    for i in n1.values():
        i = int(i)
        l1.append(i)
    res = np.mean(l1)
    return res
moy()

10.5

## 11)

### Écrire une fonction `print_admis` qui permet d’afficher le nom et la note de chacun des élèves, avec la mention "admis" si la note est supérieure ou égale à 10, ou bien "recalé" sinon.

In [ ]:
dico = {'Florian':'abs',
        'Antoine':'12',
        'Clara':'15',
        'Robert':'0',
        'Agathe':'8',
        'Erwan':'7',
        'Zoé':'20',
        'Xavier':'11',
        'Didier':'20',
        'Alain':'0',
        'Hadi':'12'}

def print_admis(dico):
    for cle,valeur in dico.items():
        if dico[cle] > 10:
            print(cle,'est admis et sa note est',valeur)
        elif dico[cle] < 10:
            print(cle,'est recalé et sa note est',valeur)

## 12)

### Modifier la fonction `print_admis` pour qu’elle stocke dans deux listes distinctes, les noms des élèves ayant réussi leur examen et ceux des élèves ayant raté leur examen.

In [2]:
dico = {'Florian':'abs',
        'Antoine':'12',
        'Clara':'15',
        'Robert':'0',
        'Agathe':'8',
        'Erwan':'7',
        'Zoé':'20',
        'Xavier':'11',
        'Didier':'20',
        'Alain':'0',
        'Hadi':'12'}

def print_admis(note):
    for cle,valeur in dic.items():
        if valeur!='abs' and float(valeur)>=10:
            L_admis=cle
            print(L_admis)
        else:
            L_recalé=cle
            print('\t',L_recalé)
    print('admis','\t recalé')
    return

NameError: name 'print_admis' is not defined

## 13)

### Écrire une fonction `saisie_notes` permettant de saisir et d’intégrer dans le dictionnaire les notes de nouveaux étudiants en supposant que les nouvelles sont respectivement contenues dans une liste de prénoms et une liste de notes.

In [6]:
def print_admis(notes):
    n1 = {key:val for key, val in notes.items() if val != 'abs'} #comprehension de dictionnaire
    admis = []
    recale = []
    for nom,note in n1.items():
        note = int(note)
        if note >= 10 :
            admis.append(nom)
        else:
            recale.append(nom)
    return(admis,recale)

In [7]:
liste_admis,liste_recale=print_admis(note)
print(liste_admis)

NameError: name 'note' is not defined

In [ ]:
def saisie_notes(a):
    print(dict)
    nb = len(dict)
    etudiants = []
    notes = []    
    dict.update(a)   
    return dict
nom = input("entrer le nom de l'élève : ")
note = int(input("entrer la note de l'élève: "))
saisie_notes({nom:note})

entrer le nom de l'élève : Antoine


## 14)

### Choisissez 5 mots de la langue française et créez un dictionnaire qui associe à chacun de ces mots sa traduction en anglais.


In [1]:
dico={'bonjour':'Hello',
      'fraise':'strawberry',
      'cochon':'pig',
      'chien ':'dog',
      'chat':'cat',}
dico

{'bonjour': 'Hello',
 'fraise': 'strawberry',
 'cochon': 'pig',
 'chien ': 'dog',
 'chat': 'cat'}

## 15)

### Ajoutez une entrée au dictionnaire de la question précédente (un nouveau mot et sa traduction). 


In [4]:
dico={'maison':'house',
      'bonjour':'Hello',
      'fraise':'strawberry',
      'cochon':'pig',
      'chien ':'dog',
      'chat':'cat',}
dico

{'maison': 'house',
 'bonjour': 'Hello',
 'fraise': 'strawberry',
 'cochon': 'pig',
 'chien ': 'dog',
 'chat': 'cat'}

In [11]:
dico={'maison':'house',
      'bonjour':'Hello',
      'fraise':'strawberry',
      'cochon':'pig',
      'chien ':'dog',
      'chat':'cat',}
dico
dico['casquette']='cap'
print(dico)

{'maison': 'house', 'bonjour': 'Hello', 'fraise': 'strawberry', 'cochon': 'pig', 'chien ': 'dog', 'chat': 'cat', 'casquette': 'cap'}


## 16)

### Écrivez une fonction `add(word1, word2, d`) qui prend en argument un mot en français, sa traduction en anglais et ajoute ces deux mots dans le dictionnaire d uniquement si `word1` n’est pas une clé du dictionnaire. Si le `word1` est déjà présent, la fonction devra afficher le texte suivant : "The word word is already as a key in d."


In [ ]:
def add (word1,  word2, d):
     if word1 in d.key:
        print("The word word is already as a key in d.")    
        d[word1]=word2
    else:
    d[word1]=word2
    return()
    

## 17)

### Écrivez une fonction `print_d` qui affiche à l’écran toutes les valeurs correspondant aux clés qui sont dans votre dictionnaire (ici, tous les mots en anglais qui apparaissent dans votre dictionnaire).


In [46]:
## 18)

### Écrivez une fonction `delete_d(car, d)` qui prend en argument un caractère car et un dictionnaire d et supprime du dictionnaire toutes les entrées correspondant à des traductions qui commencent par la lettre c.

In [13]:
def print_d(a):
    #print(len(a))
    for i in a:
        print("valeurs des mots anglais: ", a[i])
print_d(dico)

valeurs des mots anglais:  house
valeurs des mots anglais:  Hello
valeurs des mots anglais:  strawberry
valeurs des mots anglais:  pig
valeurs des mots anglais:  dog
valeurs des mots anglais:  cat
valeurs des mots anglais:  cap


18)
Écrivez une fonction delete_d(car, d) 
qui prend en argument un caractère car et un dictionnaire d et supprime du dictionnaire toutes les entrées correspondant à des traductions qui commencent par la lettre c

In [18]:
def delete_d(car, d):
    dic_new = dict()
    for cle,valeur in d.items():
        if valeur[0] != car:
            dic_new[cle]=valeur
    return dic_new

In [19]:
delete_d('c', dico)

{'maison': 'house',
 'bonjour': 'Hello',
 'fraise': 'strawberry',
 'cochon': 'pig',
 'chien ': 'dog'}