# 19. Python - Révisions

**1. Créer une liste L1 contenant tous les entiers entre 1 et 100.**

In [77]:
l = list(range(101))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


**2.Créer une fonction appelée ispair qui prend en argument un nombre et retour True si le nombre est pair et faux sinon.**

In [5]:
n = int(input("Entrez un nombre: "))
if (n % 2) == 0:
    print("{0} est Paire".format(n))
else:
    print("{0} est Impaire".format(n))   

Entrez un nombre: 12
12 est Paire


**3. Compléter le script de la fonction list_ispair qui prend en argument une liste et qui retourne une liste contenant les nombres pairs contenus dans la liste de départ en remplaçant les XXX par le code adéquat.**

In [85]:
def list_ispair(liste):
    listpair = []
    for x in liste:
        if x%2 == 0:
            listpair.append(x)
    return (listpair)

In [86]:
list_ispair(L_test)

[4, 6, 8, 12, 44, 66]

**4. Appliquer la fonction précédente à la liste `L_test` et stocker le résultat dans une variable appelée `pair`.**

In [4]:
L_test = [4,5,6,7,8,11,12,44,55,66]

In [87]:
list_ispair(L_test)

[4, 6, 8, 12, 44, 66]

**5. Afficher l'index du nombre 55 de la liste `L_test`.**

In [13]:
L_test = [4,5,6,7,8,11,12,44,55,66]
print(L_test)
L_test.index(55)

[4, 5, 6, 7, 8, 11, 12, 44, 55, 66]


8

**6. Supprimer la valeur 55 de la liste.**

In [11]:
L_test = [4,5,6,7,8,11,12,44,55,66]
del L_test[8]
print(L_test)

[4, 5, 6, 7, 8, 11, 12, 44, 66]


**7. En utilisant une boucle, affichez tous les caractères (espaces compris), un à un, de la chaîne de caractères ci-bas.**

In [82]:
chaine = "Le confinement c'est cool!"
print(chaine)  

Le confinement c'est cool!


In [88]:
chaine = "Le confinement c'est cool!"
print(chaine)
i = 0 # On appelle l'indice 'i' par convention
while i < len(chaine):
    print(chaine[i]) # On affiche le caractère à chaque tour de boucle
    i += 1

Le confinement c'est cool!
L
e
 
c
o
n
f
i
n
e
m
e
n
t
 
c
'
e
s
t
 
c
o
o
l
!


**8. En utilisant la librairie adéquate, créer un vecteur V1 contenant les valeurs 1, 2, 3 et un vecteur V2 contenant les valeurs 4, 5, 6.**

In [20]:
import numpy as np
V1= np.array([1, 2, 3,], float)
print(V1)
V2= np.array([4, 5, 6,], float)
print(V2)

[1. 2. 3.]
[4. 5. 6.]


**9. Calculer la norme L2 du vecteur V3 ci-dessous.**

In [71]:
from math import sqrt
from numpy import array
from numpy.linalg import norm
V3 = np.array([2,2,2])
print(V3)
l2 = norm(V3)
print(l2)

[2 2 2]
3.4641016151377544


**10.Créer la matrice `A` suivante.**

$$A = \begin{bmatrix} 1 & -11 & 5 \\ 2 & -15 & 8 \\ 12 & 7 & 6 \end{bmatrix}$$


In [27]:
A = np.array([[1,-11,5],[2,-15,8],[12,7,6]])
print(A)

[[  1 -11   5]
 [  2 -15   8]
 [ 12   7   6]]


**11. Calculer le déterminant de A.**

In [28]:
A = np.array([[1,-11,5],[2,-15,8],[12,7,6]])
print(A)
np.linalg.det(A)

[[  1 -11   5]
 [  2 -15   8]
 [ 12   7   6]]


-100.00000000000004

**12. Calculer l'inverse de A que vous noterez A_inv.**

In [30]:
A = np.array([[1,-11,5],[2,-15,8],[12,7,6]])
print(A)
A_inv = np.linalg.inv(A)
print(A_inv)

[[  1 -11   5]
 [  2 -15   8]
 [ 12   7   6]]
[[ 1.46 -1.01  0.13]
 [-0.84  0.54 -0.02]
 [-1.94  1.39 -0.07]]


**13. Créer la matrice identité de taille 10 que vous noterez Id_10.**

In [34]:
import numpy as np
A = np.array([[1,-11,5],[2,-15,8],[12,7,6]])
print(A)
Id_10 = np.identity(10)
print( Id_10)

[[  1 -11   5]
 [  2 -15   8]
 [ 12   7   6]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


**14. Créer une fonction `f` qui calcule l'image de la fonction f(x) suivante pour un x donné f(x) = 3x + 6 puis calculer f(2) pour vérification.**

In [37]:
def f(n):
    resultat=3*n+6
    return resultat

In [38]:
f(2)

12

**15. En utilisant les fonctions lambda, créer une fonction `f1` qui calcule le carré d'un nombre. Tester la fonction avec le nombre 5.**

In [44]:
 f1 = lambda x: x**2
  

In [45]:
f1(3)

9

**16. En utilisant les compréhensions de liste, recoder la fonction list_ispair de la question 3. Elle devra prendre en argument une liste de nombres et retourner une liste de nombres contenant les nombres entiers de la liste d'entrée. Vérifier son fonctionnement avec L_test.**

In [91]:
def list_impair(liste):
    listentier=[]
    listentier=[listentier.append(i)for i in liste %2==0 or i%2==1]
    return listentier
 list_impair()

**17. Créer un set appelé `voy` qui contient les voyelles de l'alpjabet français.**

In [95]:
import itertools as it
voy=list(voy)
all_perm = list(it.permutations(voy))
len(all_perm)

720

In [93]:
voy = set("aeiouy")
print (voy)

{'i', 'u', 'o', 'y', 'e', 'a'}


**18. Importer la librairie nécessaire aux calculs combinatoires et calculer toutes les permutations de `voy`. Combien de permutations existe-t-il?**

In [97]:
import itertools as it
voy=list(voy)
all_perm = list(it.permutations(voy))
print(all_perm)
len(all_perm)

[('A', 'I', 'Y', 'E', 'O', 'U'), ('A', 'I', 'Y', 'E', 'U', 'O'), ('A', 'I', 'Y', 'O', 'E', 'U'), ('A', 'I', 'Y', 'O', 'U', 'E'), ('A', 'I', 'Y', 'U', 'E', 'O'), ('A', 'I', 'Y', 'U', 'O', 'E'), ('A', 'I', 'E', 'Y', 'O', 'U'), ('A', 'I', 'E', 'Y', 'U', 'O'), ('A', 'I', 'E', 'O', 'Y', 'U'), ('A', 'I', 'E', 'O', 'U', 'Y'), ('A', 'I', 'E', 'U', 'Y', 'O'), ('A', 'I', 'E', 'U', 'O', 'Y'), ('A', 'I', 'O', 'Y', 'E', 'U'), ('A', 'I', 'O', 'Y', 'U', 'E'), ('A', 'I', 'O', 'E', 'Y', 'U'), ('A', 'I', 'O', 'E', 'U', 'Y'), ('A', 'I', 'O', 'U', 'Y', 'E'), ('A', 'I', 'O', 'U', 'E', 'Y'), ('A', 'I', 'U', 'Y', 'E', 'O'), ('A', 'I', 'U', 'Y', 'O', 'E'), ('A', 'I', 'U', 'E', 'Y', 'O'), ('A', 'I', 'U', 'E', 'O', 'Y'), ('A', 'I', 'U', 'O', 'Y', 'E'), ('A', 'I', 'U', 'O', 'E', 'Y'), ('A', 'Y', 'I', 'E', 'O', 'U'), ('A', 'Y', 'I', 'E', 'U', 'O'), ('A', 'Y', 'I', 'O', 'E', 'U'), ('A', 'Y', 'I', 'O', 'U', 'E'), ('A', 'Y', 'I', 'U', 'E', 'O'), ('A', 'Y', 'I', 'U', 'O', 'E'), ('A', 'Y', 'E', 'I', 'O', 'U'), ('A', '

720

**19. On tire simultanément 2 boules parmi dans une urne contenant 6 boules rouges, 3 vertes et 2 boules noires indicernables au toucher.
Combien y-a-t-il de tirages possibles ? Vérifier votre réponse avec un script.**

In [ ]:
Br={R1,R2,R3,R4,R5,R6}
Bv={V1,V2,V3}
Bn={N1,N2}

In [98]:
import itertools
boules = {'r1','r2','r3','r4','r5','r6','v1','v2','v3','n1','n2'}
k = 2
T= set(itertools.combinations(boules,k))
print(T)
print(len(T))
        

{('r5', 'n1'), ('r3', 'r6'), ('r3', 'n2'), ('r6', 'v3'), ('v2', 'n2'), ('r6', 'r2'), ('r3', 'v2'), ('r5', 'v2'), ('n1', 'v3'), ('r1', 'v2'), ('v3', 'r2'), ('r1', 'v3'), ('v2', 'v1'), ('r6', 'v2'), ('r2', 'r4'), ('r5', 'v3'), ('v2', 'r4'), ('n1', 'v1'), ('n1', 'r4'), ('r2', 'v1'), ('r6', 'n2'), ('n1', 'r3'), ('v3', 'v2'), ('r5', 'r4'), ('r3', 'r2'), ('v1', 'r4'), ('v3', 'n2'), ('n1', 'r1'), ('r2', 'n2'), ('r2', 'v2'), ('n1', 'r6'), ('r5', 'r1'), ('n1', 'n2'), ('r1', 'r6'), ('r3', 'v3'), ('r1', 'n2'), ('r6', 'r4'), ('n2', 'r4'), ('r6', 'v1'), ('n2', 'v1'), ('r5', 'n2'), ('r5', 'r6'), ('n1', 'v2'), ('r3', 'r4'), ('v3', 'r4'), ('v3', 'v1'), ('r5', 'r2'), ('r1', 'v1'), ('r5', 'v1'), ('r1', 'r2'), ('r1', 'r4'), ('n1', 'r2'), ('r3', 'v1'), ('r3', 'r1'), ('r5', 'r3')}
55


**20. Le type dictionnaire (ou tableau associatif ) permet de représenter des tableaux structurés. En effet, à chaque clé un dictionnaire associe une valeur, et cette valeur peut elle-même être une structure de donnée (liste, tuple ou un dictionnaire. . .).**

**Créer un dictionnaire vide appelé d. Ajouter y une clé `film` associée à une liste contenant 2 de vos films préférés.**

In [74]:

d={}
d.update({"film":["star war", "seigneur des anneaux"]})
print(d)

{'film': ['star  war', 'seigneurdes anneaux']}


In [99]:
d = {} 
print("le dictionnaire d créé ", d, "est VIDE!" )
d.update({"film": ["groundhog day", "time traveller's wife"]}) 
print("le dictionnaire d updaté: ", d)

le dictionnaire d créé  {} est VIDE!
le dictionnaire d updaté:  {'film': ['groundhog day', "time traveller's wife"]}
