# 22. Variables aléatoires - Espérance - Variance

Les notions abordées dans ce notebook sont:
- Les variables aléatoires
- La loi de probabilité d'une variable aléatoire discrète 
- L'indépendance de variables aléatoires
- L'espérance et la variance d'une variable aléatoire
- La covariance et la corrélation de plusieurs variables

Vous avez préalablement suivi le **topic 7** ("***Probability Introduction***") du  MOOC "*EDX - Probability and Statistics in Data Science using Python*" : https://courses.edx.org/courses/course-v1:UCSanDiegoX+DSE210x+3T2019a/course/

En complément, nous vous proposons de regarder **pour cette séance** les vidéos de Khan Academy Francophone dédiées aux variables aléatoires: https://fr.khanacademy.org/math/statistics-probability/random-variables-stats-library pour répondre aux questions posées dans <span style="color:red">**CE NOTEBOOK**</span> . 

**Sélectionner UNIQUEMENT les vidéos qui vont vous aider à répondre aux questions de ce notebook. Des questions d'entraînement vous sont également proposées (à droite de chaque section)  pour vérifier vos acquis.**

### 1. Définitions
***(Durée moyenne : 1h)***

1. Définir une variable aléatoire. Donner un exemple
2. Définir une variable aléatoire discrète et une variable aléatoire continue. Donner des exemples
3. Définir une loi de probabilité pour une variable discrète. Quelle est la loi de probabilité d'un lancer de dé équilibré? Donner d'autres exemples
4. Définir l'indépendance de deux variables aléatoires. Donner un exemple.


5. Définir une fonction de répartition pour une variable discrète. Quelles sont ses propriétés?
6. Reprendre l'exemple du lancer de dé équilibré et définir sa fonction de répartition.


7. Définir l'espérance et la variance d'une variable aléatoire. Reprendre l'exemple du lancer de dé et définir l'espérance et la variance.
8. Quelles sont les propriétés de l'espérance et de la variance? Définir l'espérance et la variance d'une somme de 2 variables.
9. Définir la covariance et la corrélation de 2 variables. Quelle est leur interprétation?


1. variables aleatoires:Une variable aléatoire réelle est une fonction qui associe un réel à chaque événement de l'univers d'une expérience aléatoire. 
 L ensemble des valeurs prises par une variable aléatoire réelle X.

 2. une variable aléatoire:
   est dite discrète lorsque l'ensemble des valeurs qu'elle peut prendre est fini ou infini       dénombrable. Ainsi, le résultat d'un lancer de dé cubique est une variable aléatoire réelle discrète car elle ne peut prendre que 6 valeurs : 1, 2, 3, 4, 5, 6.

In [ ]:
Quand le résultat d'une expérience aléatoire n’est pas un entier et
n'appartient pas à un ensemble fini,
le mieux est de définir la variable aléatoire correspondante 
directement sur R ou sur un intervalle de R .

3. En théorie des probabilités et en statistique, une loi de probabilité décrit le comportement aléatoire d'un phénomène dépendant du hasard. ... Ces premières approches sont des phénomènes discrets, c'est-à-dire dont le nombre de résultats possibles est fini ou au plus dénombrable.
1                2                3                   4                  5                6
0.16666666666 0.16666666666      0.16666666666       0.16666666666      0.16666666666 

4. L'indépendance est une notion probabiliste qualifiant 
   de manière intuitive des événements aléatoires n'ayant aucune influence l'un sur l'autre. 
   

5.La variable aléatoire réelle X est la fonction FX qui, à tout réel x, associe la probabilité d’obtenir une valeur inférieure ou égale :
F X ( x ) = P ( X ≤ x )  F_{X}(x)=\mathbb {P}(X\leq x)}.
Cette fonction est caractéristique de la loi de probabilité de la variable aléatoire. Elle permet de calculer la probabilité de chaque intervalle semi-ouvert à gauche par
P ( X ∈ ] a , b ] ) = P ( a < X ≤ b ) = F X ( b ) − F X ( a ) {P} (X\in ]a,b])=\mathbb {P} (a<X\leq b)=F_{X}(b)-F_{X}(a)} (a<X\leq b)=F_{X}(b)-F_{X}(a)}.
La fonction de répartition d'une mesure de probabilité P) est la fonction F qui à tout réel x associe.

In [ ]:
6. 

7. l'espérance et la variance d'une variable aléatoire
 l'espérance mathématique d'une variable aléatoire réelle est, intuitivement, la valeur que  l'on s'attend à trouver, en moyenne,si l'on répète un grand nombre de fois la même expérience  aléatoire. 
Elle se note E(X) et se lit « espérance de X »

la variance est une mesure de la dispersion des valeurs d'un échantillon ou d'une distribution de probabilité. Elle exprime la moyenne des carrés des écarts à la moyenne, aussi égale à la différence entre la moyenne des carrés des valeurs de la variable et le carré de la moyenne, selon le théorème de König-Huygens.

8. Quelles sont les propriétés de l'espérance et de la variance? Définir 
l'espérance et la variance d'une somme de 2 variables.

La variance est toujours positive, et ne s’annule que si les valeurs sont toutes égales.
V(x)=écarttype²

9. la covariance :
entre deux variables aléatoires est un nombre permettant de quantifier leurs écarts conjoints par rapport à leurs espérances respectives. Elle s’utilise également pour deux séries de données numériques (écarts par rapport aux moyennes).

9.bis 
la corrélation entre plusieurs variables aléatoires ou statistiques est une notion 
de liaison qui contredit leur indépendance.
Cette corrélation est très souvent réduite à la corrélation linéaire entre variables
quantitatives, c’est-à-dire l’ajustement d’une variable par rapport à l’autre par une 
relation affine obtenue par régression linéaire.

### 2. Exercices 
***(Durée moyenne : 1 à 2 heures)***

#### Exercice 1 (sans codage Python)
On vous propose le jeu suivant:
- Pour jouer, il faut payer 2€. 
- Ensuite, on lance 2 fois de suite une pièce bien équilibrée. Chaque pile rapporte 3€ et chaque face fait perdre 2€.

On considère la variable aléatoire G égale au gain algébrique du joueur. 

1. Déterminer la loi de probabilité de G et son espérance. 


In [ ]:
  
      3     -2          3      -2
      1/4   1/4       1/4      1/4

In [ ]:
import numpy as np
PX=np.array([range(1,7),sorted(np.divide(range(1,12,2),36),reverse=True)])
PY=np.array([range(1,7),np.divide(range(1,12,2),36)]); print(PX,'\n',PY)
EX=sum(np.multiply(PX[0],PX[1]))
EY=sum(np.multiply(PY[0],PY[1])); print(EX,EY)
VX=sum(np.multiply(PX[0]-3.5,PX[1]))**2
VY=sum(np.multiply(PY[0]-3.5,PY[1]))**2; print(VX,VY)
P=PX*PY
np.cov(PX,PY)

[[1.         2.         3.         4.         5.         6.        ]
 [0.30555556 0.25       0.19444444 0.13888889 0.08333333 0.02777778]] 
 [[1.         2.         3.         4.         5.         6.        ]
 [0.02777778 0.08333333 0.13888889 0.19444444 0.25       0.30555556]]
2.5277777777777777 4.472222222222222
0.9452160493827162 0.9452160493827162


array([[ 3.5       , -0.19444444,  3.5       ,  0.19444444],
       [-0.19444444,  0.01080247, -0.19444444, -0.01080247],
       [ 3.5       , -0.19444444,  3.5       ,  0.19444444],
       [ 0.19444444, -0.01080247,  0.19444444,  0.01080247]])

In [ ]:
#### Exercice 2 (sans codage Python)
On lance deux dés cubiques bien équilibrés dont les faces sont numérotées de 1 à 6.
On note X la variable aléatoire égale à l'écart entre les deux nombres sortis.
1. Déterminer la loi de probabilité de X.
2. Déterminer l'espérance de X. Interpréter.

In [ ]:
2       3       4       5       6     7     8      9    10      11   12
1/12    1/12    1/12    1/12   1/12  1/12   1/12  1/12  1/12   1/12  1/12

In [47]:
Ex=1/12*2+3*1/12+4*1/12+5*1/12+6*1/12+7*1/12+8/12+1/12*9+10/12+11/12+12/12
print(Ex)

6.416666666666667


#### Exercice 3 (sans codage Python)

Un trader a analysé plusieurs scénarios quant à l'évolution de deux actions notées A et B. On note X la variable aléatoire donnant l'évolution en euros de l'action A et Y celle donnant l'évolution en euros de l'action B. Voici les lois de probabilités de X et de Y.

|X  | -50 | 0  | 10 |40 |
|---|-----|----|----|---|
|Pxi|0.1  |0.3 | 0.5|0.1|

|Y  | -30 | 10 | 30 |
|---|-----|----|----|
|Pyi|0.3  |0.4 | 0.3|


1. Vérifier que E(X)=E(Y)
2. Calculer V(X) et V(Y)
3. Le trader ne souhaite pas prendre trop de risques et décide d'investir sur l'action la moins volatile. Quelle action lui conseillez-vous? Justifier. 

1. E(x)=-50*0.1+0.3*0+10*0.5+40*0.1=4
   E(Y)= -0.3*0.3+10*0.4+30*0.3=4

2. V(x)=((4-50)²*0.1+(4-10)²*0.3+(10-4)²*0.5+(40-4)²*0.1)/4=
2. V(y)=((4-30)²0.3+(4-10)²0.4+(10-4)²*0.3)/3=

In [ ]:
V(x)=((4+50)*(4-50)*0.1+(4-10)*(4-10)*0.3+(10-4)*0.5+(40-4)*(40-4)*0.1=
V(x)=((4+30)*(4+30)*0.1+(4-10)*(4-10)*0.3+(30-4)*0.5+(30-4)*0.1)/=      

#### Exercice 4 (avec codage Python)

On lance deux dés équilibrés, on note U1 et U2 les variables aléatoires correspondant aux résultats obtenus. 
On appelle X = min(U1,U2) et Y = max(U1,U2).

1. Donner les lois de probabilité de X et de Y
2. Calculer E(X) et E(Y)
3. Calculer V(X) et V(Y)
4. Déterminer la loi jointe de (X,Y). 
5. Déterminer la covariance de X et Y. X et Y sont-elles indépendantes? 


In [ ]:
Xmin   1       2      3    4   5   6

x      1/6    1/6    1/6  1/6  1/6  1/6

In [ ]:
Xmin   1       2      3    4   5     6

x      1/6    1/6    1/6  1/6  1/6  1/6

In [54]:
Ey=1*1/6+(2/6)+3/6+4/6+5/6+1
print(Ey)

3.5


In [12]:
import numpy as np
PX=np.array([range(1,7),sorted(np.divide(range(1,12,2),36),reverse=True)])
PY=np.array([range(1,7),np.divide(range(1,12,2),36)]); print(PX,'\n',PY)


P=PX*PY
np.cov(PX,PY)


[[1.         2.         3.         4.         5.         6.        ]
 [0.30555556 0.25       0.19444444 0.13888889 0.08333333 0.02777778]] 
 [[1.         2.         3.         4.         5.         6.        ]
 [0.02777778 0.08333333 0.13888889 0.19444444 0.25       0.30555556]]
2.5277777777777777 4.472222222222222
0.9452160493827162 0.9452160493827162


array([[ 3.5       , -0.19444444,  3.5       ,  0.19444444],
       [-0.19444444,  0.01080247, -0.19444444, -0.01080247],
       [ 3.5       , -0.19444444,  3.5       ,  0.19444444],
       [ 0.19444444, -0.01080247,  0.19444444,  0.01080247]])

In [13]:
import numpy as np
PX=np.array([range(1,7),sorted(np.divide(range(1,12,2),36),reverse=True)])
PY=np.array([range(1,7),np.divide(range(1,12,2),36)]); print(PX)

[[1.         2.         3.         4.         5.         6.        ]
 [0.30555556 0.25       0.19444444 0.13888889 0.08333333 0.02777778]]


In [14]:
EX=sum(np.multiply(PX[0],PX[1]))
EY=sum(np.multiply(PY[0],PY[1])); print(EX,EY)

2.5277777777777777 4.472222222222222


In [15]:
VX=sum(np.multiply(PX[0]-3.5,PX[1]))**2
VY=sum(np.multiply(PY[0]-3.5,PY[1]))**2; print(VX,VY)

0.9452160493827162 0.9452160493827162


In [16]:
P=PX*PY
np.cov(PX,PY)

array([[ 3.5       , -0.19444444,  3.5       ,  0.19444444],
       [-0.19444444,  0.01080247, -0.19444444, -0.01080247],
       [ 3.5       , -0.19444444,  3.5       ,  0.19444444],
       [ 0.19444444, -0.01080247,  0.19444444,  0.01080247]])

#### Exercice 5 (avec codage Python)
1. Simuler N lancers de 2 dés équilibrés. X désigne le résultat du 1er dé et Y le résultat du second.
2. Comparer la moyenne empirique de X à son espérance théorique
3. Comparer l'écart-type empirique de X à l'écart-type théorique
4. Comparer la covariance empirique à la covariance théorique de X et Y

- N prend comme valeurs 10, 100, 1000,10000,100000

In [ ]:
 def lancer2(n):
    i=0
    liste=[]
    while i<n:
        X=rd.randint(1,6)
        Y=rd.randint(1,6)
        liste.append((X,Y))
        i+=1
    return liste
A=lancer(10)
B=lancer(100)
C=lancer(1000)
D=lancer(10000)
E=lancer(10000)

In [20]:
import numpy.random as rd
A=lancer2(10)
p=[]
for i in A:
    x=(1/6)*i
    p.append(x)
C=sum(p)
E=21/6
print(A,sum(p),E)

[1, 4, 2, 1, 2, 4, 2, 2, 3, 4] 4.166666666666667 3.5


In [23]:
import statistics as  st
N = [10,100,1000,10000, 100000]
N2 = [10,100,1000,10000, 100000]
X  =  []
Y = []
J = 0
j = 0
for i in N : 
    while j< i : 
        d=randint(1,6)
        X.append(d)
        j = j+1
    print(len(X))
    sigmaX = st.pstdev(X)
    MoyX = st.mean(X)
    print ("la moyenne arithmétique de X est ", MoyX)
    print ("l'écart type empirique de X est ",sigmaX)
for I in N2 : 
    while J < I : 
        d=randint(1,6)
        Y.append(d)
        J = J+1 
    print(len(Y))
    sigmaY = st.pstdev(Y)
    MoyY = st.mean(Y)
    print("la moyenne empirique de Y est ", MoyY)
    print("l'écart type empirique de Y est ",sigmaY)
Covxy = np.cov(X,Y)
print ("la covarience de X,Y est ", Covxy)

10
la moyenne arithmétique de X est  4
l'écart type empirique de X est  1.4142135623730951
100
la moyenne arithmétique de X est  3.35
l'écart type empirique de X est  1.6575584454250776
1000
la moyenne arithmétique de X est  3.455
l'écart type empirique de X est  1.6964595485893557
10000
la moyenne arithmétique de X est  3.5295
l'écart type empirique de X est  1.6890025902881263
100000
la moyenne arithmétique de X est  3.49887
l'écart type empirique de X est  1.707764246932228
10
la moyenne empirique de Y est  3
l'écart type empirique de Y est  1.5491933384829668
100
la moyenne empirique de Y est  3.22
l'écart type empirique de Y est  1.7696327302578918
1000
la moyenne empirique de Y est  3.446
l'écart type empirique de Y est  1.7283182577291718
10000
la moyenne empirique de Y est  3.4727
l'écart type empirique de Y est  1.7092263483810446
100000
la moyenne empirique de Y est  3.48739
l'écart type empirique de Y est  1.7082742718603474
la covarience de X,Y est  [[2.91648789 0.00952585]