# Introduction Classification d'images (chiffres manuscrits)


## Consigne du jour


### Objectifs 
Apprendre à entrainer un modèle de classification d'images avec du Machine Learning.




In [ ]:
pip install keras

In [9]:
import numpy as np
#import tensorflow
#from tensorflow import keras
#import keras
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('TkAgg')
import seaborn as sns
from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score 
from sklearn.metrics import confusion_matrix, precision_recall_curve, roc_curve, auc, log_loss


## I. Données 

**1. Charger les données avec la cellule suivante.**

In [11]:
#from keras.datasets import mnist
#(X_train, y_train), (X_test, y_test) = mnist.load_data()

**2. Afficher quelques données. Afficher les dimensions des données. Quelle est la particularité de vos données?**

In [13]:
import numpy as np 
import pandas as pd 
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt 
import seaborn as sns
data_image_X_train=pd.read_csv('X_train.csv', sep=',', encoding='utf8')
data_image_X_train.head(10)

Unnamed: 0  0  1  2  3  4  5  6  7  8  ...  774  775  776  777  778  779  \
0           0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
1           1  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
2           2  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
3           3  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
4           4  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
5           5  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
6           6  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
7           7  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
8           8  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
9           9  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   

   780  781  782  783  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0  
5    0    0    0    0  
6    0    0    0    0  
7    0    0    0    0  
8    0    0    0    0  
9    0    0    0    0  

[10 rows x 785 columns]

In [14]:
data_image_X_test=pd.read_csv('X_test.csv', sep=',', encoding='utf8')
data_image_X_test.head(10)

Unnamed: 0  0  1  2  3  4  5  6  7  8  ...  774  775  776  777  778  779  \
0           0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
1           1  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
2           2  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
3           3  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
4           4  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
5           5  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
6           6  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
7           7  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
8           8  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
9           9  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   

   780  781  782  783  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0  
5    0    0    0    0  
6    0    0    0    0  
7    0    0    0    0  
8    0    0    0    0  
9    0    0    0    0  

[10 rows x 785 columns]

In [15]:
data_image_y_test=pd.read_csv('y_test.csv', sep=',', encoding='utf8')
data_image_y_test.head(10)

Unnamed: 0  0
0           0  7
1           1  2
2           2  1
3           3  0
4           4  4
5           5  1
6           6  4
7           7  9
8           8  5
9           9  9

In [16]:
data_image_y_train=pd.read_csv('y_train.csv', sep=',', encoding='utf8')
data_image_y_train.head(10)

Unnamed: 0  0
0           0  5
1           1  0
2           2  4
3           3  1
4           4  9
5           5  2
6           6  1
7           7  3
8           8  1
9           9  4

In [17]:
data_image_X_train.shape

(60000, 785)

In [18]:
data_image_X_test.shape

(10000, 785)

In [19]:
data_image_y_test.shape

(10000, 2)

In [20]:
data_image_y_train.shape

(60000, 2)

In [21]:
data_image_X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 785 entries, Unnamed: 0 to 783
dtypes: int64(785)
memory usage: 359.3 MB


In [22]:
data_image_X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Columns: 785 entries, Unnamed: 0 to 783
dtypes: int64(785)
memory usage: 59.9 MB


In [23]:
data_image_y_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
Unnamed: 0    10000 non-null int64
0             10000 non-null int64
dtypes: int64(2)
memory usage: 156.4 KB


In [24]:
data_image_y_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 2 columns):
Unnamed: 0    60000 non-null int64
0             60000 non-null int64
dtypes: int64(2)
memory usage: 937.6 KB


In [25]:
data_image_X_train.describe()

Unnamed: 0        0        1        2        3        4        5  \
count  60000.000000  60000.0  60000.0  60000.0  60000.0  60000.0  60000.0   
mean   29999.500000      0.0      0.0      0.0      0.0      0.0      0.0   
std    17320.652413      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%    14999.750000      0.0      0.0      0.0      0.0      0.0      0.0   
50%    29999.500000      0.0      0.0      0.0      0.0      0.0      0.0   
75%    44999.250000      0.0      0.0      0.0      0.0      0.0      0.0   
max    59999.000000      0.0      0.0      0.0      0.0      0.0      0.0   

             6        7        8  ...           774           775  \
count  60000.0  60000.0  60000.0  ...  60000.000000  60000.000000   
mean       0.0      0.0      0.0  ...      0.200433      0.088867   
std        0.0      0.0      0.0  ...      6.042472      3.956189   
min        0.0      0.0      0.0  ...      0.000000      0.000000   
25%        0.0      0.0      0.0  ...      0.000000      0.000000   
50%        0.0      0.0      0.0  ...      0.000000      0.000000   
75%        0.0      0.0      0.0  ...      0.000000      0.000000   
max        0.0      0.0      0.0  ...    254.000000    254.000000   

                776           777           778         779      780      781  \
count  60000.000000  60000.000000  60000.000000  60000.0000  60000.0  60000.0   
mean       0.045633      0.019283      0.015117      0.0020      0.0      0.0   
std        2.839845      1.686770      1.678283      0.3466      0.0      0.0   
min        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
25%        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
50%        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
75%        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
max      253.000000    253.000000    254.000000     62.0000      0.0      0.0   

           782      783  
count  60000.0  60000.0  
mean       0.0      0.0  
std        0.0      0.0  
min        0.0      0.0  
25%        0.0      0.0  
50%        0.0      0.0  
75%        0.0      0.0  
max        0.0      0.0  

[8 rows x 785 columns]

In [26]:
data_image_X_test.describe()

Unnamed: 0        0        1        2        3        4        5  \
count  10000.00000  10000.0  10000.0  10000.0  10000.0  10000.0  10000.0   
mean    4999.50000      0.0      0.0      0.0      0.0      0.0      0.0   
std     2886.89568      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.00000      0.0      0.0      0.0      0.0      0.0      0.0   
25%     2499.75000      0.0      0.0      0.0      0.0      0.0      0.0   
50%     4999.50000      0.0      0.0      0.0      0.0      0.0      0.0   
75%     7499.25000      0.0      0.0      0.0      0.0      0.0      0.0   
max     9999.00000      0.0      0.0      0.0      0.0      0.0      0.0   

             6        7        8  ...           774           775  \
count  10000.0  10000.0  10000.0  ...  10000.000000  10000.000000   
mean       0.0      0.0      0.0  ...      0.179300      0.163600   
std        0.0      0.0      0.0  ...      5.674149      5.736072   
min        0.0      0.0      0.0  ...      0.000000      0.000000   
25%        0.0      0.0      0.0  ...      0.000000      0.000000   
50%        0.0      0.0      0.0  ...      0.000000      0.000000   
75%        0.0      0.0      0.0  ...      0.000000      0.000000   
max        0.0      0.0      0.0  ...    253.000000    253.000000   

                776         777      778      779      780      781      782  \
count  10000.000000  10000.0000  10000.0  10000.0  10000.0  10000.0  10000.0   
mean       0.052600      0.0006      0.0      0.0      0.0      0.0      0.0   
std        2.420004      0.0600      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0000      0.0      0.0      0.0      0.0      0.0   
25%        0.000000      0.0000      0.0      0.0      0.0      0.0      0.0   
50%        0.000000      0.0000      0.0      0.0      0.0      0.0      0.0   
75%        0.000000      0.0000      0.0      0.0      0.0      0.0      0.0   
max      156.000000      6.0000      0.0      0.0      0.0      0.0      0.0   

           783  
count  10000.0  
mean       0.0  
std        0.0  
min        0.0  
25%        0.0  
50%        0.0  
75%        0.0  
max        0.0  

[8 rows x 785 columns]

In [27]:
data_image_y_train.describe()

Unnamed: 0             0
count  60000.000000  60000.000000
mean   29999.500000      4.453933
std    17320.652413      2.889270
min        0.000000      0.000000
25%    14999.750000      2.000000
50%    29999.500000      4.000000
75%    44999.250000      7.000000
max    59999.000000      9.000000

In [28]:
data_image_y_test.describe()

Unnamed: 0             0
count  10000.00000  10000.000000
mean    4999.50000      4.443400
std     2886.89568      2.895865
min        0.00000      0.000000
25%     2499.75000      2.000000
50%     4999.50000      4.000000
75%     7499.25000      7.000000
max     9999.00000      9.000000

**3. Redimensionner vos matrices afin qu'elles soient valables en entrée de vos modèles.**

In [ ]:
#data_Image.reshape()

**4. Transformer vos données en float.**

In [30]:
data_image_X_train.astype(float)

Unnamed: 0    0    1    2    3    4    5    6    7    8  ...  774  775  \
0             0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1             1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2             2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3             3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
4             4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...           ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995     59995.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
59996     59996.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
59997     59997.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
59998     59998.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
59999     59999.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

       776  777  778  779  780  781  782  783  
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...    ...  ...  ...  ...  ...  ...  ...  ...  
59995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
59996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
59997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
59998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
59999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[60000 rows x 785 columns]

In [31]:
data_image_X_test.astype(float)

Unnamed: 0    0    1    2    3    4    5    6    7    8  ...  774  775  \
0            0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1            1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2            2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3            3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
4            4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...          ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995      9995.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
9996      9996.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
9997      9997.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
9998      9998.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
9999      9999.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

      776  777  778  779  780  781  782  783  
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  ...  
9995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[10000 rows x 785 columns]

### **5. Les valeurs des pixels variant entre 0 et 255, nous allons diviser toutes les valeurs par 255 afin d'obtenir un niveau de pixels entre 0 et 1.**

In [85]:
data_image_X_train=data_image_X_train/255
data_image_X_test=data_image_X_test/255
data_image_y_test=data_image_y_test/255
data_image_y_train=data_image_y_train/255

**6. Afficher le premier élément de X_train et le premier élément de X_test.**

In [86]:
data_image_X_train.head(1)

0    1    2    3    4    5    6    7    8    9  ...  774  775  776  777  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

   778  779  780  781  782  783  
0  0.0  0.0  0.0  0.0  0.0  0.0  

[1 rows x 784 columns]

In [87]:
data_image_X_test.head(1)

Unnamed: 0    0    1    2    3    4    5    6    7    8  ...  774  775  \
0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

   776  777  778  779  780  781  782  783  
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[1 rows x 785 columns]

**7. Executer le code suivant vous permettant d'afficher quelques images du jeu de données.**

In [ ]:
plt.figure(figsize=(7.195, 3.841), dpi=100)
for i in range(200):
    plt.subplot(10,20,i+1)
    plt.imshow(X_train[i,:].reshape([28,28]), cmap='gray')
    plt.axis('off')
plt.show()

In [88]:
data_image_X_train
data_image_X_test
data_image_y_train
data_image_y_test

Unnamed: 0         0
0       0.000000  0.027451
1       0.003922  0.007843
2       0.007843  0.003922
3       0.011765  0.000000
4       0.015686  0.015686
...          ...       ...
9995   39.196078  0.007843
9996   39.200000  0.011765
9997   39.203922  0.015686
9998   39.207843  0.019608
9999   39.211765  0.023529

[10000 rows x 2 columns]

In [74]:
data_image_X_train = data_image_X_train.loc[:, ~data_image_X_train.columns.str.contains('^Unnamed')]
data_image_y_train = data_image_y_train.loc[:, ~data_image_y_train.columns.str.contains('^Unnamed')]
#data_image_x_test = data_image_x_test.loc[:, ~data_image_x_test.str.contains('^Unnamed')]
#data_image_y_test = data_image_y_test.loc[:, ~data_image_y_test.columns.str.contains('^Unnamed')]

In [80]:
data_image_X_train.shape

(60000, 784)

In [40]:
data_image_X_test.shape

(10000, 785)

In [41]:
data_image_y_train.shape

(60000, 1)

In [81]:
data_image_X_test.shape

(10000, 785)

# II. Régression logistique 

##### Régression logistique avec scikit learn 

In [82]:
from sklearn.linear_model import LogisticRegression
#help(LogisticRegression)

In [1]:
clf = LogisticRegression().fit(data_image_X_train,data_image_y_train)

NameError: name 'LogisticRegression' is not defined

In [2]:
data_image_X_train

NameError: name 'data_image_X_train' is not defined

In [64]:
clf.coef_

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [65]:
clf.intercept_

array([-2.63985402, -1.4106872 , -2.4322212 , -2.4050114 , -2.12729507,
       -2.22848355, -2.3438593 , -1.96944246, -2.74871007, -2.29630613])

In [67]:
reg = LogisticRegression()
reg.fit(data_image_X_train,data_image_y_train)
#4
print(reg.coef_,'\n',reg.intercept_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 
 [-2.63985402 -1.4106872  -2.4322212  -2.4050114  -2.12729507 -2.22848355
 -2.3438593  -1.96944246 -2.74871007 -2.29630613]


# III. Modèles

##### L'objectif de cette partie est de trouver le modèle le plus performant. Pour cela, vous devez lancer tous les modèles de classification que vous connaissez et déterminer quel modèle est le plus performant. Pour chacun des modèles utilisés, rappeler brièvement comment fonctionne la méthode en quelques mots. Vous devez, lorsque cela est nécesssaire, effectuer une gridSearch.

In [71]:
#modele de classification  
#modele knn gridsearch
#modele svm gridsearch
#modele Rondomforest gridsearch 
#modele  
#navais bayes  
#decission tree
#Adaboost

In [56]:
pip install --upgrade tensorflow

  Using cached https://files.pythonhosted.org/packages/af/50/d7da24189d95e2084bb1cc350a8e4acdf1b0c9b3d57def7a348f0d9cb062/tensorflow-2.2.0-cp37-cp37m-win_amd64.whl
  Using cached https://files.pythonhosted.org/packages/a1/6b/7f62017e3f0b32438dd90bdc1ff0b7b1448b6cb04a1ed84f37b6de95cd7b/h5py-2.10.0-cp37-cp37m-win_amd64.whl
  Using cached https://files.pythonhosted.org/packages/61/51/046cbc61c7607e5ecead6ff1a9453fba5e7e47a5ea8d608cc7036586a5ef/scipy-1.4.1-cp37-cp37m-win_amd64.whl
  Found existing installation: h5py 2.9.0
    Uninstalling h5py-2.9.0:
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Accès refusé: 'c:\\programdata\\anaconda3\\lib\\site-packages\\h5py-2.9.0.dist-info\\INSTALLER'
Consider using the `--user` option or check the permissions.



In [68]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
Ytrain=le.fit_transform(Ytrain)
Ytest=le.fit_transform(Ytest)

NameError: name 'Ytrain' is not defined

In [67]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import classification_report

### Etude de Svm

In [94]:
param_grid ={10,50,100,200,'kernel':['rbf'],'sigmoid']}
param_grid
gscv = GridSearchCV(CSV(),param_grid,cv=3)
gscv.fit(X_train,y)
gscv.best_params_
gscv.best_score_
best_model=gscv.best.estimator_
pred_train=best_model.predict(data_image_X_train)
pred_test=best_model_predict(data_image_y_train)
print(pred_train,pred_test)

SyntaxError: invalid syntax (<ipython-input-94-5c35cf26db4e>, line 1)

### Etude de Randonforest 

In [50]:
alpha_randomforestclassifier = [1e-15, 1e-10, 1e-8, 1e-6, 1e-4, 1e-3, 1e-2, 1e-1, 1, 5, 10, 20]

### Etude de navais bayes 

In [98]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler
#from sklearn.naive_bayes import GaussianNB, MultinomialNB, ComplementNB, BernoulliNB, CategoricalNB
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import classification_report


In [96]:
#"L'indice de diversité de gini : probabilité pour chaque élément d'être choisi multipliée
#par la probabilité qu'il soit mal classé"""
#L'entropie au lieu d'utiliser les probabilités simples applique le log2 des probabilités"""

**Regrouper vos résultats dans un dataframe et déterminer le modèle le plus performant.**
